### ISSUE TITLE
Fallback language not working with multiple fields

### ISSUE THREAD

**Issue by pgcd** [edoburu/django-parler#75]
I might be doing something wrong here but it looks like the fallback doesn't work when the translation exists for a different field.
I have a model like:
```
class MyModel(TranslatableModel):
    title = TranslatedField(any_language=True)
    description = TranslatedField(any_language=True)
    translations = TranslatedFields(
        title=models.CharField(max_length=255),
        description=models.TextField(blank=True),
    )
```

If I create an object with a translation for both fields in 'en', then add a translated description for 'de', when I retrieve that object in 'de' I would expect to have the German description and the English title (as a fallback). What happens instead is that, since the German translation exists, I get the German description and an empty title.
I took a quick look at the tests and it appears this case is not covered, since they all seem to deal with a single "title" field. Of course, maybe I'm just doing something wrong, in which case please let me know.

**Comment by vdboor** [comment]
Hi, this is indeed expected behavior; when you create a translation, Django stores a complete model with title + description field. The fallback is only used when there is no translation model stored for a specific language, and in your case, there is, even though it's an explicit blank field. From what I can tell, that could also be on purpose.

If you want an empty description to mean, take the contents from the fallback, that's fine. That could either be built into parler (using something like `TranslatedField(any_language=True, fallback_when_empty=True)`), or by adding some `get_description()` method to your model that makes two calls on it's own using `safe_translation_getter`

**Comment by pgcd** [comment]
That makes perfect sense - given the way the ORM works, it would become crazily expensive for lists of objects with multiple translated and variously missing fields. 
I will try to solve my problem otherwise (by adding the missing values from the default language when creating the translation). 
One thing I believe should be changed, though, is the documentation: there are quite a few places where it says "if the **attribute** is missing" or something to that effect, and I suppose it should be changed to "if the **translation object** is missing", for clarity.

**Comment by vdboor** [comment]
Thanks for the update! I can't find the doc area's you're looking for. Can you provide some help or a pull request? So far it seems to distinguish between "attributes" and "translations" clearly.
