### ISSUE TITLE
Integration with django-mptt fails with the example in the doc under mptt 0.6

### ISSUE THREAD

**Issue by georgema1982** [edoburu/django-parler#93]
Under mptt 0.6, the example codes for integration with django-mptt in the doc (http://django-parler.readthedocs.org/en/latest/advanced/mptt.html) won't work. You would see errors like:

ValueError: @python_2_unicode_compatible cannot be applied to Category because it doesn't define __str__().

I have to swap TranslatableModel and MPTTModel's positions to make python_2_unicode_compatible happy.

A similar issue is here: https://github.com/edoburu/django-parler/issues/91

Maybe TranslatableModel has to be the last parent if python_2_unicode_compatible is used?

**Comment by vdboor** [comment]
Hi!

The example was written with the latest package versions and Python 3 support in mind. Nothing prevents you off course to remove ` @python_2_unicode_compatible` and just use `__unicode__()` instead of `__str__()`.

**Comment by vdboor** [comment]
I find this quite a strange issue. I've just released django-categories-i18n, where I didn't run into this issue at all. I didn't get this error regarding `@python_2_unicode_compatible`, this just worked nicely.

For an example how to use parler + mptt, you can now also look at: https://github.com/edoburu/django-categories-i18n Note this package uses a separate `TranslatedFieldsModel` instead of the `TranslatedFields(..)` construct, but the class design remains the same.
